const codeItems = [
  {
    codeId: 1,
    img: require("../images/html-icon.svg").default,
    name: "HTML 5",
    description:
      "My work reflects a meticulous attention to detail and an unwavering commitment to best practices, resulting in web experiences that seamlessly blend form and function. My expertise extends beyond the basics, as seen in my thoughtful use of semantic markup, responsive design principles, and commitment to cross-browser compatibility, ensuring a flawless user experience across diverse platforms. ",
    projects: ["Library Landing Page", "Coffeeshop"],
    projectURL: ["https://mnunezsa95.github.io/se_project_library/", "https://mnunezsa95.github.io/se_project_coffeeshop/"],
  },
  {
    codeId: 2,
    img: require("../images/css-icon.svg").default,
    name: "CSS 3",
    description: "abc",
    projects: ["Library Landing Page", "Coffeeshop", "Around the U.S", "Bank Marketing Site", "Pig Game", "Number Game"],
    projectURL: [
      "https://mnunezsa95.github.io/se_project_library/",
      "https://mnunezsa95.github.io/se_project_coffeeshop/",
      "https://mnunezsa95.github.io/se_project_aroundtheus/",
      "https://bank-marketing-site-marlon-nunez.netlify.app/",
      "https://pig-game-demo-marlon-nunez.netlify.app/",
      "https://number-guess-game-demo-marlon-nunez.netlify.app/",
    ],
  },
  {
    codeId: 3,
    img: require("../images/javascript-icon.svg").default,
    name: "JavaScript",
    description: "abc",
    projects: ["Around the U.S", "Bank App", "Workout App", "Forkify App", "Bank Marketing Site", "Pig Game", "Number Game"],
    projectURL: [
      "https://mnunezsa95.github.io/se_project_aroundtheus/",
      "https://simple-bank-app-demo-mn.netlify.app/",
      "https://workout-app-marlon-nunez.netlify.app/",
      "https://forkify-marlon-nunez.netlify.app/",
      "https://bank-marketing-site-marlon-nunez.netlify.app/",
      "https://pig-game-demo-marlon-nunez.netlify.app/",
      "https://number-guess-game-demo-marlon-nunez.netlify.app/",
    ],
  },
  {
    codeId: 4,
    img: require("../images/react-icon.svg").default,
    name: "React.js",
    description: "abc",
    projects: ["What to Wear App", "News Explorer App", "Pizza Menu"],
    projectURL: ["https://www.wtwear.mooo.com/", "https://www.news-explorer.mooo.com/", "https://pizza-menu-demo-marlon-nunez.netlify.app/"],
  },
  {
    codeId: 5,
    img: require("../images/node-icon.svg").default,
    name: "Node.js",
    description: "abc",
    projects: ["What to Wear App", "News Explorer App"],
    projectURL: ["https://www.wtwear.mooo.com/", "https://www.news-explorer.mooo.com/"],
  },
  {
    codeId: 6,
    img: require("../images/python-icon.svg").default,
    name: "Python",
    description: "abc",
    projects: [],
    projectURL: [],
  },
  {
    codeId: 7,
    img: require("../images/mongodb-icon.svg").default,
    name: "MongoDB",
    projects: ["What to Wear App", "News Explorer App"],
    projectURL: ["https://www.wtwear.mooo.com/", "https://www.news-explorer.mooo.com/"],
  },
  {
    codeId: 8,
    img: require("../images/postgreSQL-icon.svg").default,
    name: "PostgreSQL",
    projects: [],
    projectURL: [],
  },
  {
    codeId: 9,
    img: require("../images/googlecloud-icon.svg").default,
    name: "Google Cloud",
    projects: ["What to Wear App", "News Explorer App"],
    projectURL: ["https://www.wtwear.mooo.com/", "https://www.news-explorer.mooo.com/"],
  },
  {
    codeId: 10,
    img: require("../images/npm-icon.svg").default,
    name: "NPM",
    projects: [],
    projectURL: [],
  },
  {
    codeId: 11,
    img: require("../images/git-icon.svg").default,
    name: "Git",
    description: "abc",
    projects: [],
    projectURL: [],
  },
  {
    codeId: 12,
    img: require("../images/github-icon-code.svg").default,
    name: "GitHub",
    projects: ["GitHub Projects"],
    projectURL: ["https://github.com/mnunezsa95"],
  },
];

export default codeItems;
