const educationItems = [
  {
    educationId: 4,
    institutionName: "TripleTen",
    institutionCity: "Remote",
    institutionState: null,
    startYear: 2024,
    graduationYear: 2024,
    duration: "9 Months",
    degree: "Data Science Certificate",
    major: "Data Science",
    minor: null,
    GPA: null,
  },
  {
    educationId: 3,
    institutionName: "TripleTen",
    institutionCity: "Remote",
    institutionState: null,
    startYear: 2023,
    graduationYear: 2023,
    duration: "10 Months",
    degree: "Full-Stack Software Engineering Certificate",
    major: "Software Engineering",
    minor: null,
    GPA: null,
  },
  {
    educationId: 2,
    institutionName: "Boston University",
    institutionCity: "Boston",
    institutionState: "Massachusetts",
    startYear: 2018,
    graduationYear: 2020,
    duration: "2 Years",
    degree: "Masters of Education (M.Ed)",
    major: "Curriculum & Teaching",
    minor: null,
    GPA: 4.0,
  },
  {
    educationId: 1,
    institutionName: "Tulane University",
    institutionCity: "New Orleans",
    institutionState: "Louisiana",
    startYear: 2014,
    graduationYear: 2018,
    duration: "4 Years",
    degree: "Bachelors of Science and Public Health (BSPH)",
    major: "Public Health, Neuroscience",
    minor: null,
    GPA: 3.58,
  },
];

export default educationItems;
